defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs

sass:
  style: :compressed

baseurl: "/marathon"
highlighter: pygments
lsi: false
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]
safe: true
source: .
